
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_healthscribe_development

test:
  <<: *default
  database: my_healthscribe_test

production:
  <<: *default
  database: my_healthscribe_production
  username: my_healthscribe
  password: <%= ENV["MY_HEALTHSCRIBE_DATABASE_PASSWORD"] %>
